### ISSUE TITLE
Broken Link KDiskFree in System Administration.

### ISSUE THREAD

**Issue by shivanshu-semwal** [francoism90/awesome-kde#4]
This link [https://www.kde.org/applications/system/kdiskfree/](https://www.kde.org/applications/system/kdiskfree/) redirects to, [https://apps.kde.org/en/kdiskfree](https://apps.kde.org/en/kdiskfree), which gives `404` error. [https://apps.kde.org/en/kdf](https://apps.kde.org/en/kdf) this is the correct link.

**Comment by francoism90** [comment]
@shivanshu-semwal Why did you close this issue? I'll fix the link, ty. :)

**Comment by francoism90** [comment]
Fixed. :)
