### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [francoism90/awesome-kde#8]
Hello, there are a few broken links:

- [ ] https://apps.kde.org/kwalletmanager5/ (file: README.md, status code: 404)
- [ ] https://umbrello.kde.org/ (file: README.md, error: ENOTFOUND)
- [ ] https://apps.kde.org/wacomtablet/ (file: README.md, status code: 404)

**Comment by francoism90** [comment]
@ndsvw Thanks for reporting.

I'll try to fix them later this week. But if you could send me a PR with the links fixed or maybe removed when out-dated, that would be great. :)
